### PR TITLE
update master

### PR DESCRIPTION
**Pull request by avilleret**
I don't know why yet but ofnode disappeared few days ago.
and my fork appear to be based on yours now despite mine is 31 commits ahead.
I have a fresh clone of `ofnode/of` repository made a week ago or so and then I push it back to my repo.
So maybe you could update yours with it ?

BTW do you know why ofnode repo disappeared ?
All known issues links in the README.md are broken since they point to ofnode gist.

### CODE REVIEW

**Comment by aspeteRakete** [comment]
Hi there. Tried to contact constantine a few times to get some info on his motives but never received an answer.

**Comment by symbolix** [comment]
I am also curious to hear on this topic. I was digging on the OF forums, almost like a proper archaeology. People sounded quite positive about the CMake implementation and the discussions seemed to go in the right direction. However, none of the referenced stuff works any more.

**Comment by avilleret** [comment]
hi there, 

I've updated of to 0.9.3
only tested on linux for now

**Comment by avilleret** [comment]
forgot this PR,  I resuscitated the project here : https://github.com/ofnode
feel free to participate

**Pull request closed without merging**
